config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :movies
  resources :rating, only: [:create, :update]

  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'
  has_many :rating_for_movies, dependent: :destroy

  validates :user_id, :title, :description, :category, presence: true
  validates :description, length: {minimum: 5}
end

app/models/rating_for_movie.rb
class RatingForMovie < ApplicationRecord
  belongs_to :movies, foreign_key: 'movie_id', class_name: 'Movie'

  validates :movie_id, uniqueness: {scope: :user_id}
  validates :movie_id, :user_id, :rating, presence: true

  rating_amount = (1..10).to_a

  validates :rating, inclusion: {
    in: rating_amount,
    message: "must be between 1 and 10"
  }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  has_many :movies
  has_many :rating_for_movies, through: :movies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def actions_admin
    redirect_to movies_path unless current_user.has_role?(:admin)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :current_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :actions_admin, only: [:new, :edit, :destroy, :create]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    render :new
  end

  def edit
    render :edit
  end

  def create
    @movie = current_user.movies.create(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
     if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  def show

  end

private

  def current_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    (params.require(:movie).permit(:title, :category, :description))
  end

end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  before_action :authenticate_user!

  def create
    rating_for_movie = RatingForMovie.new
    rating_for_movie.user_id = current_user.id
    rating_for_movie.rating = rating
    rating_for_movie.movie_id = movie_id
    rating_for_movie.save

    redirect_to movies_path
  end

  def update
    @rating_for_movie = RatingForMovie.find_or_initialize_by(user_id: current_user.id, movie_id: movie_id)
    @rating_for_movie.rating = rating
    @rating_for_movie.save!

    @movies = Movie.all

    render 'movies/index'
  end

private

  def rating
    params.require(:rating)
  end

  def movie_id
    params.require(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>   
    <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>

<%= form_with model: @movie, url: movie_path, method: :put, local: true do |f| %>

  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :category %>:
  <%= f.text_field :category %>

  <%= f.label :description %>:
  <%= f.text_field :description %>
  
  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      h1, h2, h3, h4, h5, h6, p {color: white;}
      body { background-color: #000 }
    </style>
  </head>

  <body>
    <div class="container">

      <div class="row gy-4">
        <%= link_to "new movie", new_movie_path %>
        <% @movies.each do |movie| %>
          <div class="col-3">
            <h4><%= link_to movie.title, edit_movie_path(movie) %> </h4>
            <div class="card" style="width: 15rem;">
              <!-- <img src="https://upload.wikimedia.org/wikipedia/ru/thumb/6/69/Riddick_poster.jpg/210px-Riddick_poster.jpg" class="card-img-top" alt="img"> -->
            </div>
            <p>category: <%= movie.category %></p>
            <p><%= truncate(movie.description) %></p>
            <h5>Rating <%= movie.average_rating %></h5>
              <%= form_with model: @rating, url: rating_path(id: movie.id), method: :put, local: true do |f| %>

                <%= f.text_field :rating %>
                
                <%= f.submit %>
              <h5>My assessment <%=  @rating_for_movie.rating if @rating_for_movie %></h5>
            <% end %>
            <!-- <td><%= link_to "Delete", movie, method: :delete %></td> -->
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/movies/new.html.erb
<h1>Movies#new</h1>

<%= form_with model: @movie, url: movies_path, method: :post, local: true do |f| %>

  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :category %>:
  <%= f.text_field :category %>

  <%= f.label :description %>:
  <%= f.text_field :description %>
  
  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>